### ISSUE TITLE
knitting doesn't work after pulling Charlie's edits

### ISSUE THREAD

**Issue by Jody-O** [rin3-spring-2021/WAGAP_poverty_analysis#1]
@charliejhadley I've pulled your edits and can run all the code chunks, resulting in the nice rainbow chart you added with 'grouped_ethnicities'.  But when I try to knit, I get this error message:

Error: Problem with `mutate()` input `please_select_the_races_or_ethnicities_you_most_identify_with`.
x invalid multibyte string, element 12
i Input `please_select_the_races_or_ethnicities_you_most_identify_with` is `(function (x) ...`.

I discovered that the mutate error occurs in code chunk 10 - which has no mutate function in the script.  When I comment out all of chunk 10, the knit works.  What is going on with this error?  Why can't code chunk 10 create a tabyl?  I'm pretty sure it created a big ugly table in the knitted html before I pulled your edits but it doesn't look like you changed anything in that code chunk - so why won't it work now?

Also, I want my tables in the report to look more formatted with a nice font, etc.  Will we be learning to do this later?  If not, can you show some example code for creating a formatted table in the knitted document?

Thank you!

**Comment by charliejhadley** [comment]
The document wasn't knitting due to a multibyte character in the .csv file, I've pushed an update containing a utf-8 formatted .csv and modified the code to read in from that file. Here's a video explaining that https://share.getcloudapp.com/9Zux8G51

Here's another video talking about formatting tables https://share.getcloudapp.com/04uAJedl

If you have follow up questions please do tag me - otherwise could you close this issue? Thanks!

**Comment by Jody-O** [comment]
Thanks for the help with the .csv utf-8 formatting.
I'm going to work on making my tables formatted later this week and will open a new issue if I need more help.  Meanwhile I'll get my week 5 assignment pushed with it's own plot format issues :)
